services:
  traefik:
    image: traefik:v3.3
    ports:
      - 443:443
      - 5432:5432
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/traefik/certs:/etc/traefik/certs:Z
    networks:
      - traefik
    restart: unless-stopped
    env_file: .env
    environment:
      TRAEFIK_ENTRYPOINTS_HTTPS: true
      TRAEFIK_ENTRYPOINTS_HTTPS_ADDRESS: :443
      TRAEFIK_PROVIDERS_DOCKER: true
      TRAEFIK_PROVIDERS_DOCKER_NETWORK: traefik
      TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT: false
      TRAEFIK_CERTIFICATESRESOLVERS_MYRESOLVER: true
      TRAEFIK_CERTIFICATESRESOLVERS_MYRESOLVER_ACME_EMAIL: ${LETS_ENCRYPT_EMAIL}
      TRAEFIK_CERTIFICATESRESOLVERS_MYRESOLVER_ACME_TLSCHALLENGE: true
      TRAEFIK_CERTIFICATESRESOLVERS_MYRESOLVER_ACME_STORAGE: /etc/traefik/certs/myresolver.json
      # TRAEFIK_CERTIFICATESRESOLVERS_MYRESOLVER_ACME_CASERVER: https://acme-staging-v02.api.letsencrypt.org/directory
    healthcheck:
      test: traefik healthcheck

  backend:
    build:
      context: ./
      target: production-backend
    # image: ...
    env_file: .env
    networks:
      - traefik
    labels:
      traefik.enable: "true"
      traefik.http.routers.backend.rule: "Host(`${DOMAIN}`) && PathPrefix(`/api`)"
      traefik.http.routers.backend.entrypoints: https
      traefik.http.routers.backend.tls: "true"
      traefik.http.routers.backend.tls.certResolver: myresolver
      traefik.http.routers.backend.tls.domains[0].main: ${DOMAIN}

  frontend:
    build:
      context: ./
      target: production-frontend
    # image: ...
    # ports:
    #   - 5173:5733
    depends_on:
      backend:
        condition: service_started
        restart: true
    networks:
      - traefik
    labels:
      traefik.enable: "true"
      traefik.http.routers.frontend.rule: Host(`${DOMAIN}`)
      traefik.http.routers.frontend.entrypoints: https
      traefik.http.routers.frontend.tls: "true"
      traefik.http.routers.frontend.tls.certResolver: myresolver
      traefik.http.routers.frontend.tls.domains[0].main: ${DOMAIN}

networks:
  traefik:
    external: true