enum Phases {
    WELCOME = "WELCOME",
    VOTING = "VOTING",
    POSITION_SELECTION = "POSITION_SELECTION",
    ROUND_START = "ROUND_START",
    CHARACTER_SELECTION = "CHARACTER_SELECTION",
    ROLE_ASSIGNMENT = "ROLE_ASSIGNMENT",
    DAY = "DAY",
    NIGHT = "NIGHT",
    DEBATE = "DEBATE",
    BODYGUARD_DEFENSE = "BODYGUARD_DEFENSE", 
    DETECTIVE_CHECK = "DETECTIVE_CHECK",
    MAFIA_VOTING = "MAFIA_VOTING", 
    ROUND_END = "ROUND_END", 
    GAME_END = "GAME_END", 
    VOTING_OVERTIME = "VOTING_OVERTIME",
    LOBBY = "LOBBY"
}
 